language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: gcc
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: clang
      env: MATRIX_EVAL=

    - os: osx
      compiler: clang
      env: MATRIX_EVAL=

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - make -j2 Hugin
  - cd test_files
  - ../hugin/Hugin test
  - tar xzf test3_v1.tar.gz 
  - tar xzf test3_v2.tar.gz
  - ../hugin/Hugin diff -v1 test3_v1 -v2 test3_v2 --dryRun --flashSize 30
